version: '3'

services:
  nginx:
    image: nginx:latest
    environment:
      - BITNAMI_DEBUG=true
      - NGINX_HTTP_PORT_NUMBER=8080
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/share/nginx/html/
    labels:
      - "traefik.enable=true"
      #SSL
      #Troque pelo seu dominio
      - "traefik.http.routers.sites.rule=Host(`semana.landmatos.com.br`)"
      - "traefik.http.routers.sites.entrypoints=web,websecure"
      - "traefik.http.routers.sites.tls.certresolver=leresolver"
    networks:
      - sites

networks:
  sites:
    external: true